import Layout from '@components/layout';
import { IServiceCardProps, ServiceCard } from '@components/servicecard';
import Head from 'next/head';
import React from 'react';
import styles from '@styles/Home.module.css';
import { useSelector } from 'react-redux';
import { IStoreState } from '@redux/reducer';

let datas: IServiceCardProps[] = [
	{ serviceName: 'API', etat: 'actif'},
	{ serviceName: 'Database', etat: 'inactif'},
	{ serviceName: 'PI', etat: 'maintenance'},
	{ serviceName: 'WebApp', etat: 'enattente'}
];

export default function Etat(){

	const maintenanceState = useSelector((state: IStoreState) => state.maintenance);

	if (maintenanceState) {
		datas.map((data) => {
			data.etat = 'maintenance';
		});
	} else {
		datas = [
			{ serviceName: 'API', etat: 'actif'},
			{ serviceName: 'Database', etat: 'inactif'},
			{ serviceName: 'PI', etat: 'maintenance'},
			{ serviceName: 'WebApp', etat: 'enattente'}
		];
	}

	return (
		<Layout>
			<Head>
				<title>AssociativeEndives - Etat des Services</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="preload"
					href="/fonts/Roboto/Roboto-Regular.ttf"
					as="font"
					crossOrigin=""
				/>
			</Head>
			<div className={styles.title}>Etat des Services</div>
			<div className={styles.card_service_grid}>
				{
					datas.map((data, index) => 
						<ServiceCard
							key={index}
							serviceName={data.serviceName}
							etat={data.etat}
						></ServiceCard>
					)
				}
			</div>
		</Layout>
	)
}
