import React from 'react';
import Layout from '@components/layout';
import style from '@styles/Maintenance.module.css';
import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import { maintenance, normal } from '@redux/action';
import { IStoreState } from '@redux/reducer';


export default function Maintenance(){

	const maintenanceState = useSelector((state: IStoreState) => state.maintenance)

	const dispatch = useDispatch()

	let button =
	(!maintenanceState) ?
		<div className={style.maintenance_button} onClick={() => dispatch(maintenance())}>
				<div className={style.maintenance_button_text}>Mode Maintenance</div>
		</div>
	:
		<div className={style.maintenance_button_active} onClick={() => dispatch(normal())}>
				<div className={style.maintenance_button_text}>Mode Normal</div>
		</div>

	return (
		<Layout>
			<Head>
				<title>AssociativeEndives - Maintenance</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="preload"
					href="/fonts/Roboto/Roboto-Regular.ttf"
					as="font"
					crossOrigin=""
				/>
			</Head>
			<div className={style.maintenance_card_container}>
				<div className={style.maintenance_card}>
					<div className={style.title}>Maintenance</div>
					<div className={style.maintenance_box}>
						<div className={style.maintenance_textbox}>
						Pour activer le mode maintenance, appuyer sur le bouton ci-dessous,
						Tant que ce mode est actif aucune mesure ne sera réalisable
						ainsi que la sauvegarde des données. A la sortie du mode maintenance,
						une vérifications sera faîtes sur toute l’infrastucture
						</div>
						{button}
					</div>
				</div>
			</div>
		</Layout>
	)
}
